version: '3'

services:

  wordpress:
    image: wordpress
    env_file:
      - ./env/production/.env
    restart: always
    volumes:
      - ./wordpress:/var/www/html
      - ./themes/SAA:/var/www/html/wp-content/themes/SAA
    ports:
      - '8080:80'
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: mysqld --user=mysql --innodb-use-native-aio=0
    env_file:
      - ./env/production/.env
    restart: always
    volumes:
      - ./db-datadir:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - '3306:3307'

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    restart: always
    environment:
      DOMAINS: >-
        test.kaizumaki.net -> http://wordpress:8080,
#      STAGE: 'production'
#      FORCE_RENEW: 'true'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./ssl-certs:/var/lib/https-portal
#      - ./nginx/ssl/ssl.conf:/var/lib/nginx-conf/test.kaizumaki.net.ssl.conf.erb:ro
    depends_on:
      - wordpress
