version: '3'

services:

  db:
    image: mysql:8.0
    command: mysqld --user=mysql --innodb-use-native-aio=0
    env_file:
      - ./env/production/.env
    volumes:
      - ./db-datadir:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'
    tty: true

  web:
    build:
      context: ./
      dockerfile: Dockerfile-production
    command: bash -c "python manage.py collectstatic --noinput && gunicorn config.wsgi -b 0.0.0.0:8080"
    env_file:
      - ./env/production/.env
    volumes:
      - .:/code
      - ./static:/code/static
    expose:
      - '8080'
    depends_on:
      - db

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    restart: always
    environment:
      DOMAINS: >-
        kaizumaki.net -> http://web:8080,
        mail.kaizumaki.net
      STAGE: 'production'
#      FORCE_RENEW: 'true'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./ssl-certs:/var/lib/https-portal
      - ./static:/var/www/vhosts/kaizumaki.net/static
      - ./nginx/ssl/ssl.conf:/var/lib/nginx-conf/kaizumaki.net.ssl.conf.erb:ro
    depends_on:
      - web

  mail:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: kaizumaki.net
    ports:
      - '25:25'
      - '143:143'
      - '587:587'
      - '993:993'
    volumes:
      - ./maildata:/var/mail
      - ./mailstate:/var/mail-state
      - ./mailconfig/:/tmp/docker-mailserver/
      - ./ssl-certs:/etc/letsencrypt:ro
    environment:
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1
      - ONE_DIR=1
      - SSL_TYPE=letsencrypt
      - PERMIT_DOCKER=network
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
