CREATE DATABASE IF NOT EXISTS "$MYSQL_DATABASE" CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE USER IF NOT EXISTS '"$MYSQL_USER"'@'localhost' IDENTIFIED BY '"$MYSQL_PASSWORD"';
GRANT ALL PRIVILEGES ON "$MYSQL_USER".* TO '"$MYSQL_USER"'@'localhost' WITH GRANT OPTION;
CREATE USER IF NOT EXISTS '"$MYSQL_USER"'@'0.0.0.0' IDENTIFIED BY '"$MYSQL_PASSWORD"';
GRANT ALL PRIVILEGES ON "$MYSQL_USER".* TO '"$MYSQL_USER"'@'0.0.0.0' WITH GRANT OPTION;
CREATE USER IF NOT EXISTS '"$MYSQL_USER"'@'%' IDENTIFIED BY '"$MYSQL_PASSWORD"';
GRANT ALL PRIVILEGES ON "$MYSQL_USER".* TO '"$MYSQL_USER"'@'%' WITH GRANT OPTION;
